services:
  # Web service for your Express server
  - type: web
    name: stock-proxy
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
    # Note: Using PostgreSQL database (no local disk storage needed)
    # Make sure to set DATABASE_URL environment variable in Render dashboard