/**
 * Shared Stock Data Module
 * Contains comprehensive stock lists for all markets
 * Used by both backend scanner and frontend DTI interface
 */

const nifty50Stocks = [
    { name: "Adani Enterprises", symbol: "ADANIENT.NS" },
    { name: "Adani Ports", symbol: "ADANIPORTS.NS" },
    { name: "Apollo Hospitals", symbol: "APOLLOHOSP.NS" },
    { name: "Asian Paints", symbol: "ASIANPAINT.NS" },
    { name: "Axis Bank", symbol: "AXISBANK.NS" },
    { name: "Bajaj Auto", symbol: "BAJAJ-AUTO.NS" },
    { name: "Bajaj Finance", symbol: "BAJFINANCE.NS" },
    { name: "Bajaj Finserv", symbol: "BAJAJFINSV.NS" },
    { name: "BPCL", symbol: "BPCL.NS" },
    { name: "Bharti Airtel", symbol: "BHARTIARTL.NS" },
    { name: "Britannia", symbol: "BRITANNIA.NS" },
    { name: "CIPLA", symbol: "CIPLA.NS" },
    { name: "Coal India", symbol: "COALINDIA.NS" },
    { name: "Divis Labs", symbol: "DIVISLAB.NS" },
    { name: "Dr Reddy's Labs", symbol: "DRREDDY.NS" },
    { name: "Eicher Motors", symbol: "EICHERMOT.NS" },
    { name: "Grasim", symbol: "GRASIM.NS" },
    { name: "HCL Tech", symbol: "HCLTECH.NS" },
    { name: "HDFC Bank", symbol: "HDFCBANK.NS" },
    { name: "Hero MotoCorp", symbol: "HEROMOTOCO.NS" },
    { name: "Hindalco", symbol: "HINDALCO.NS" },
    { name: "HUL", symbol: "HINDUNILVR.NS" },
    { name: "ICICI Bank", symbol: "ICICIBANK.NS" },
    { name: "IndusInd Bank", symbol: "INDUSINDBK.NS" },
    { name: "InfoEdge", symbol: "NAUKRI.NS" },
    { name: "Infosys", symbol: "INFY.NS" },
    { name: "ITC", symbol: "ITC.NS" },
    { name: "JSW Steel", symbol: "JSWSTEEL.NS" },
    { name: "Kotak Mahindra", symbol: "KOTAKBANK.NS" },
    { name: "L&T", symbol: "LT.NS" },
    { name: "M&M", symbol: "M&M.NS" },
    { name: "Maruti Suzuki", symbol: "MARUTI.NS" },
    { name: "Nestle India", symbol: "NESTLEIND.NS" },
    { name: "NTPC", symbol: "NTPC.NS" },
    { name: "ONGC", symbol: "ONGC.NS" },
    { name: "Power Grid", symbol: "POWERGRID.NS" },
    { name: "Reliance", symbol: "RELIANCE.NS" },
    { name: "SBI", symbol: "SBIN.NS" },
    { name: "SBI Life", symbol: "SBILIFE.NS" },
    { name: "Shree Cement", symbol: "SHREECEM.NS" },
    { name: "Sun Pharma", symbol: "SUNPHARMA.NS" },
    { name: "TCS", symbol: "TCS.NS" },
    { name: "Tata Consumer", symbol: "TATACONSUM.NS" },
    { name: "Tata Motors", symbol: "TATAMOTORS.NS" },
    { name: "Tata Steel", symbol: "TATASTEEL.NS" },
    { name: "Tech Mahindra", symbol: "TECHM.NS" },
    { name: "Titan", symbol: "TITAN.NS" },
    { name: "UltraTech Cement", symbol: "ULTRACEMCO.NS" },
    { name: "UPL", symbol: "UPL.NS" },
    { name: "Wipro", symbol: "WIPRO.NS" }
];

const niftyNext50Stocks = [
    { name: "Abbott India", symbol: "ABBOTINDIA.NS" },
    { name: "Adani Green Energy", symbol: "ADANIGREEN.NS" },
    { name: "Adani Total Gas", symbol: "ATGL.NS" },
    { name: "Berger Paints", symbol: "BERGEPAINT.NS" },
    { name: "BEL", symbol: "BEL.NS" },
    { name: "Bosch", symbol: "BOSCHLTD.NS" },
    { name: "Canara Bank", symbol: "CANBK.NS" },
    { name: "Dmart", symbol: "DMART.NS" },
    { name: "Godrej Consumer", symbol: "GODREJCP.NS" },
    { name: "Godrej Properties", symbol: "GODREJPROP.NS" },
    { name: "HAL", symbol: "HAL.NS" },
    { name: "Havells", symbol: "HAVELLS.NS" },
    { name: "HDFC Life", symbol: "HDFCLIFE.NS" },
    { name: "ICICI Lombard", symbol: "ICICIGI.NS" },
    { name: "ICICI Pru Life", symbol: "ICICIPRULI.NS" },
    { name: "Indian Hotels", symbol: "INDHOTEL.NS" },
    { name: "Indraprastha Gas", symbol: "IGL.NS" },
    { name: "InterGlobe Aviation", symbol: "INDIGO.NS" },
    { name: "IRCTC", symbol: "IRCTC.NS" },
    { name: "Jindal Steel", symbol: "JINDALSTEL.NS" },
    { name: "L&T Infotech", symbol: "LTI.NS" },
    { name: "Lupin", symbol: "LUPIN.NS" },
    { name: "Marico", symbol: "MARICO.NS" },
    { name: "Max Financial", symbol: "MFSL.NS" },
    { name: "Mindtree", symbol: "MINDTREE.NS" },
    { name: "Motherson Sumi", symbol: "MOTHERSUMI.NS" },
    { name: "Mphasis", symbol: "MPHASIS.NS" },
    { name: "MRF", symbol: "MRF.NS" },
    { name: "Muthoot Finance", symbol: "MUTHOOTFIN.NS" },
    { name: "NMDC", symbol: "NMDC.NS" },
    { name: "OFSS", symbol: "OFSS.NS" },
    { name: "Oil India", symbol: "OIL.NS" },
    { name: "Page Industries", symbol: "PAGEIND.NS" },
    { name: "Petronet LNG", symbol: "PETRONET.NS" },
    { name: "Pidilite", symbol: "PIDILITIND.NS" },
    { name: "PNB", symbol: "PNB.NS" },
    { name: "Polycab", symbol: "POLYCAB.NS" },
    { name: "Procter & Gamble", symbol: "PGHH.NS" },
    { name: "SBI Cards", symbol: "SBICARD.NS" },
    { name: "Shriram Transport", symbol: "SRTRANSFIN.NS" },
    { name: "Siemens", symbol: "SIEMENS.NS" },
    { name: "Torrent Pharma", symbol: "TORNTPHARM.NS" },
    { name: "Trent", symbol: "TRENT.NS" },
    { name: "Tube Investments", symbol: "TIINDIA.NS" },
    { name: "UBL", symbol: "UBL.NS" },
    { name: "Voltas", symbol: "VOLTAS.NS" },
    { name: "Zomato", symbol: "ZOMATO.NS" },
    { name: "Zydus Life", symbol: "ZYDUSLIFE.NS" },
    { name: "3M India", symbol: "3MINDIA.NS" },
    { name: "Zee Entertainment", symbol: "ZEEL.NS" }
];

const niftyMidcap150Stocks = [
    { name: "Adani Power", symbol: "ADANIPOWER.NS" },
    { name: "Adani Transmission", symbol: "ADANITRANS.NS" },
    { name: "Alkem Labs", symbol: "ALKEM.NS" },
    { name: "Amara Raja", symbol: "AMARAJABAT.NS" },
    { name: "Ashok Leyland", symbol: "ASHOKLEY.NS" },
    { name: "Aurobindo Pharma", symbol: "AUROPHARMA.NS" },
    { name: "Balkrishna Industries", symbol: "BALKRISIND.NS" },
    { name: "Bandhan Bank", symbol: "BANDHANBNK.NS" },
    { name: "Bank of Baroda", symbol: "BANKBARODA.NS" },
    { name: "Bharat Electronics", symbol: "BEL.NS" },
    { name: "Bharat Forge", symbol: "BHARATFORG.NS" },
    { name: "Biocon", symbol: "BIOCON.NS" },
    { name: "Cadila Healthcare", symbol: "CADILAHC.NS" },
    { name: "Central Bank", symbol: "CENTRALBK.NS" },
    { name: "CESC", symbol: "CESC.NS" },
    { name: "Cholamandalam Finance", symbol: "CHOLAFIN.NS" },
    { name: "City Union Bank", symbol: "CUB.NS" },
    { name: "Colgate Palmolive", symbol: "COLPAL.NS" },
    { name: "Coromandel Intl", symbol: "COROMANDEL.NS" },
    { name: "Cummins India", symbol: "CUMMINSIND.NS" },
    { name: "Dabur India", symbol: "DABUR.NS" },
    { name: "Deepak Nitrite", symbol: "DEEPAKNTR.NS" },
    { name: "Dixon Technologies", symbol: "DIXON.NS" },
    { name: "Edelweiss Financial", symbol: "EDELWEISS.NS" },
    { name: "Embassy Office Parks", symbol: "EMBASSY.NS" },
    { name: "Endurance Technologies", symbol: "ENDURANCE.NS" },
    { name: "Equitas Holdings", symbol: "EQUITAS.NS" },
    { name: "Federal Bank", symbol: "FEDERALBNK.NS" },
    { name: "Fortis Healthcare", symbol: "FORTIS.NS" },
    { name: "GAIL India", symbol: "GAIL.NS" },
    { name: "General Insurance Corp", symbol: "GICRE.NS" },
    { name: "Gillette India", symbol: "GILLETTE.NS" },
    { name: "Glenmark Pharma", symbol: "GLENMARK.NS" },
    { name: "GMR Infrastructure", symbol: "GMRINFRA.NS" },
    { name: "Godrej Agrovet", symbol: "GODREJAGRO.NS" },
    { name: "Godrej Industries", symbol: "GODREJIND.NS" },
    { name: "Gujarat Gas", symbol: "GUJGASLTD.NS" },
    { name: "Gujarat State Petronet", symbol: "GSPL.NS" },
    { name: "Hindustan Petroleum", symbol: "HINDPETRO.NS" },
    { name: "HDFC Asset Management", symbol: "HDFCAMC.NS" },
    { name: "Honeywell Automation", symbol: "HONAUT.NS" },
    { name: "IDBI Bank", symbol: "IDBI.NS" },
    { name: "IDFC First Bank", symbol: "IDFCFIRSTB.NS" },
    { name: "Indian Bank", symbol: "INDIANB.NS" },
    { name: "Indian Overseas Bank", symbol: "IOB.NS" },
    { name: "Indus Towers", symbol: "INDUSTOWER.NS" },
    { name: "Info Edge", symbol: "NAUKRI.NS" },
    { name: "IOC", symbol: "IOC.NS" },
    { name: "Ipca Labs", symbol: "IPCALAB.NS" },
    { name: "JB Chemicals", symbol: "JBCHEPHARM.NS" },
    { name: "JK Cement", symbol: "JKCEMENT.NS" },
    { name: "JSW Energy", symbol: "JSWENERGY.NS" },
    { name: "Jubilant FoodWorks", symbol: "JUBLFOOD.NS" },
    { name: "Kajaria Ceramics", symbol: "KAJARIACER.NS" },
    { name: "Kansai Nerolac", symbol: "KANSAINER.NS" },
    { name: "KEI Industries", symbol: "KEI.NS" },
    { name: "L&T Technology", symbol: "LTTS.NS" },
    { name: "Laurus Labs", symbol: "LAURUSLABS.NS" },
    { name: "Mahindra Finance", symbol: "MAHINDCIE.NS" },
    { name: "Manappuram Finance", symbol: "MANAPPURAM.NS" },
    { name: "Max Healthcare", symbol: "MAXHEALTH.NS" },
    { name: "Metropolis Healthcare", symbol: "METROPOLIS.NS" },
    { name: "Minda Industries", symbol: "MINDAIND.NS" },
    { name: "Motherson Sumi", symbol: "MOTHERSUMI.NS" },
    { name: "NBCC India", symbol: "NBCC.NS" },
    { name: "Navin Fluorine", symbol: "NAVINFLUOR.NS" },
    { name: "New India Assurance", symbol: "NIACL.NS" },
    { name: "NHPC", symbol: "NHPC.NS" },
    { name: "Oberoi Realty", symbol: "OBEROIRLTY.NS" },
    { name: "Oriental Bank", symbol: "ORIENTBANK.NS" },
    { name: "PFC", symbol: "PFC.NS" },
    { name: "Phoenix Mills", symbol: "PHOENIXLTD.NS" },
    { name: "PI Industries", symbol: "PIIND.NS" },
    { name: "Piramal Enterprises", symbol: "PEL.NS" },
    { name: "Polyplex Corp", symbol: "POLYPLEX.NS" },
    { name: "Prestige Estates", symbol: "PRESTIGE.NS" },
    { name: "PVR INOX", symbol: "PVRINOX.NS" },
    { name: "Quess Corp", symbol: "QUESS.NS" },
    { name: "Rail Vikas Nigam", symbol: "RVNL.NS" },
    { name: "Ramco Cements", symbol: "RAMCOCEM.NS" },
    { name: "Rashtriya Chemicals", symbol: "RCF.NS" },
    { name: "RBL Bank", symbol: "RBLBANK.NS" },
    { name: "Redington", symbol: "REDINGTON.NS" },
    { name: "Restaurant Brands Asia", symbol: "RBA.NS" },
    { name: "SBI Life", symbol: "SBILIFE.NS" },
    { name: "Schaeffler India", symbol: "SCHAEFFLER.NS" },
    { name: "Solar Industries", symbol: "SOLARINDS.NS" },
    { name: "Sobha", symbol: "SOBHA.NS" },
    { name: "SAIL", symbol: "SAIL.NS" },
    { name: "Supreme Industries", symbol: "SUPREMEIND.NS" },
    { name: "Suzlon Energy", symbol: "SUZLON.NS" },
    { name: "Symphony", symbol: "SYMPHONY.NS" },
    { name: "Tamil Nadu Newsprint", symbol: "TNPL.NS" },
    { name: "Tata Chemicals", symbol: "TATACHEM.NS" },
    { name: "Tata Communications", symbol: "TATACOMM.NS" },
    { name: "Tata Power", symbol: "TATAPOWER.NS" },
    { name: "TeamLease Services", symbol: "TEAMLEASE.NS" },
    { name: "Thermax", symbol: "THERMAX.NS" },
    { name: "Thyrocare Technologies", symbol: "THYROCARE.NS" },
    { name: "Torrent Power", symbol: "TORNTPOWER.NS" },
    { name: "TV18 Broadcast", symbol: "TV18BRDCST.NS" },
    { name: "Union Bank", symbol: "UNIONBANK.NS" },
    { name: "Varun Beverages", symbol: "VBL.NS" },
    { name: "Vedanta", symbol: "VEDL.NS" },
    { name: "VIP Industries", symbol: "VIPIND.NS" },
    { name: "Welspun India", symbol: "WELSPUNIND.NS" },
    { name: "Yes Bank", symbol: "YESBANK.NS" }
];

const ftse100Stocks = [
    { name: "3i Group", symbol: "III.L" },
    { name: "Admiral Group", symbol: "ADM.L" },
    { name: "Ashtead Group", symbol: "AHT.L" },
    { name: "Associated British Foods", symbol: "ABF.L" },
    { name: "AstraZeneca", symbol: "AZN.L" },
    { name: "Aviva", symbol: "AV.L" },
    { name: "BAE Systems", symbol: "BA.L" },
    { name: "Barclays", symbol: "BARC.L" },
    { name: "British American Tobacco", symbol: "BATS.L" },
    { name: "BT Group", symbol: "BT-A.L" },
    { name: "Bunzl", symbol: "BNZL.L" },
    { name: "Burberry Group", symbol: "BRBY.L" },
    { name: "Centrica", symbol: "CNA.L" },
    { name: "Coca-Cola HBC", symbol: "CCH.L" },
    { name: "Compass Group", symbol: "CPG.L" },
    { name: "CRH", symbol: "CRH.L" },
    { name: "DCC", symbol: "DCC.L" },
    { name: "Diageo", symbol: "DGE.L" },
    { name: "Easyjet", symbol: "EZJ.L" },
    { name: "Experian", symbol: "EXPN.L" },
    { name: "Flutter Entertainment", symbol: "FLTR.L" },
    { name: "FTSE Russell", symbol: "FTRE.L" },
    { name: "GSK", symbol: "GSK.L" },
    { name: "Haleon", symbol: "HLN.L" },
    { name: "Halma", symbol: "HLMA.L" },
    { name: "Hargreaves Lansdown", symbol: "HL.L" },
    { name: "HSBC Holdings", symbol: "HSBA.L" },
    { name: "Imperial Brands", symbol: "IMB.L" },
    { name: "Informa", symbol: "INF.L" },
    { name: "InterContinental Hotels", symbol: "IHG.L" },
    { name: "International Airlines Group", symbol: "IAG.L" },
    { name: "Intertek Group", symbol: "ITRK.L" },
    { name: "JD Sports Fashion", symbol: "JD.L" },
    { name: "Johnson Matthey", symbol: "JMAT.L" },
    { name: "Kingfisher", symbol: "KGF.L" },
    { name: "Land Securities", symbol: "LAND.L" },
    { name: "Legal & General", symbol: "LGEN.L" },
    { name: "Lloyds Banking Group", symbol: "LLOY.L" },
    { name: "London Stock Exchange", symbol: "LSEG.L" },
    { name: "M&G", symbol: "MNG.L" },
    { name: "Marks & Spencer", symbol: "MKS.L" },
    { name: "Melrose Industries", symbol: "MRO.L" },
    { name: "Mondi", symbol: "MNDI.L" },
    { name: "National Grid", symbol: "NG.L" },
    { name: "NatWest Group", symbol: "NWG.L" },
    { name: "Next", symbol: "NXT.L" },
    { name: "Ocado Group", symbol: "OCDO.L" },
    { name: "Pearson", symbol: "PSON.L" },
    { name: "Pershing Square Holdings", symbol: "PSH.L" },
    { name: "Phoenix Group Holdings", symbol: "PHNX.L" },
    { name: "Prudential", symbol: "PRU.L" },
    { name: "Reckitt", symbol: "RKT.L" },
    { name: "RELX", symbol: "REL.L" },
    { name: "Rentokil Initial", symbol: "RTO.L" },
    { name: "Rightmove", symbol: "RMV.L" },
    { name: "Rolls-Royce Holdings", symbol: "RR.L" },
    { name: "Royal Mail", symbol: "RMG.L" },
    { name: "Sage Group", symbol: "SGE.L" },
    { name: "Sainsbury", symbol: "SBRY.L" },
    { name: "Schroders", symbol: "SDR.L" },
    { name: "Scottish Mortgage Investment Trust", symbol: "SMT.L" },
    { name: "Segro", symbol: "SGRO.L" },
    { name: "Severn Trent", symbol: "SVT.L" },
    { name: "Shell", symbol: "SHEL.L" },
    { name: "Smith & Nephew", symbol: "SN.L" },
    { name: "Smiths Group", symbol: "SMIN.L" },
    { name: "Spirax-Sarco Engineering", symbol: "SPX.L" },
    { name: "SSE", symbol: "SSE.L" },
    { name: "Standard Chartered", symbol: "STAN.L" },
    { name: "Taylor Wimpey", symbol: "TW.L" },
    { name: "Tesco", symbol: "TSCO.L" },
    { name: "The Berkeley Group Holdings", symbol: "BKG.L" },
    { name: "Unilever", symbol: "ULVR.L" },
    { name: "United Utilities", symbol: "UU.L" },
    { name: "Vodafone Group", symbol: "VOD.L" },
    { name: "Weir Group", symbol: "WEIR.L" },
    { name: "Whitbread", symbol: "WTB.L" },
    { name: "WPP", symbol: "WPP.L" }
];

const ftse250Stocks = [
    { name: "4imprint Group", symbol: "FOUR.L" },
    { name: "888 Holdings", symbol: "888.L" },
    { name: "AA", symbol: "AA.L" },
    { name: "Abcam", symbol: "ABC.L" },
    { name: "Abrdn", symbol: "ABDN.L" },
    { name: "ACS", symbol: "ACS.L" },
    { name: "AJ Bell", symbol: "AJB.L" },
    { name: "Alliance Trust", symbol: "ATST.L" },
    { name: "Alongi", symbol: "ALN.L" },
    { name: "Anglo American Platinum", symbol: "AMS.L" },
    { name: "Ashmore Group", symbol: "ASHM.L" },
    { name: "Auto Trader Group", symbol: "AUTO.L" },
    { name: "B&M European Value Retail", symbol: "BME.L" },
    { name: "Balfour Beatty", symbol: "BBY.L" },
    { name: "Bank of Georgia Group", symbol: "BGEO.L" },
    { name: "Barratt Developments", symbol: "BDEV.L" },
    { name: "Beazley", symbol: "BEZ.L" },
    { name: "Bellway", symbol: "BWY.L" },
    { name: "Berkeley Group Holdings", symbol: "BKG.L" },
    { name: "Big Yellow Group", symbol: "BYG.L" },
    { name: "Bodycote", symbol: "BOY.L" },
    { name: "Boohoo Group", symbol: "BOO.L" },
    { name: "BP", symbol: "BP.L" },
    { name: "Britvic", symbol: "BVIC.L" },
    { name: "Brooks Macdonald Group", symbol: "BRK.L" },
    { name: "Burford Capital", symbol: "BUR.L" },
    { name: "Bytes Technology Group", symbol: "BYTS.L" },
    { name: "Cairn Energy", symbol: "CNE.L" },
    { name: "Card Factory", symbol: "CARD.L" },
    { name: "Carnival", symbol: "CCL.L" },
    { name: "Cineworld Group", symbol: "CINE.L" },
    { name: "Clarkson", symbol: "CKN.L" },
    { name: "Close Brothers Group", symbol: "CBG.L" },
    { name: "CMC Markets", symbol: "CMCX.L" },
    { name: "Coats Group", symbol: "COA.L" },
    { name: "Computacenter", symbol: "CCC.L" },
    { name: "ConvaTec Group", symbol: "CTEC.L" },
    { name: "Cranswick", symbol: "CWK.L" },
    { name: "Currys", symbol: "CURY.L" },
    { name: "Darktrace", symbol: "DARK.L" },
    { name: "De La Rue", symbol: "DLAR.L" },
    { name: "Deliveroo", symbol: "ROO.L" },
    { name: "Diploma", symbol: "DPLM.L" },
    { name: "Direct Line Insurance Group", symbol: "DLG.L" },
    { name: "Discoverie Group", symbol: "DSCV.L" },
    { name: "Domino's Pizza Group", symbol: "DOM.L" },
    { name: "Drax Group", symbol: "DRX.L" },
    { name: "DS Smith", symbol: "SMDS.L" },
    { name: "Dunelm Group", symbol: "DNLM.L" },
    { name: "Elementis", symbol: "ELM.L" },
    { name: "Energean", symbol: "ENOG.L" },
    { name: "Essentra", symbol: "ESNT.L" },
    { name: "Euromoney Institutional Investor", symbol: "ERM.L" },
    { name: "Evraz", symbol: "EVR.L" },
    { name: "FDM Group", symbol: "FDM.L" },
    { name: "Ferrexpo", symbol: "FXPO.L" },
    { name: "FirstGroup", symbol: "FGP.L" },
    { name: "Foxtons Group", symbol: "FOXT.L" },
    { name: "Funding Circle Holdings", symbol: "FCH.L" },
    { name: "Gamma Communications", symbol: "GAMA.L" },
    { name: "GB Group", symbol: "GBG.L" },
    { name: "Genuit Group", symbol: "GEN.L" },
    { name: "Genus", symbol: "GNS.L" },
    { name: "Glencore", symbol: "GLEN.L" },
    { name: "Go-Ahead Group", symbol: "GOG.L" },
    { name: "Goodwin", symbol: "GDWN.L" },
    { name: "Grafton Group", symbol: "GFTU.L" },
    { name: "Grainger", symbol: "GRI.L" },
    { name: "Great Portland Estates", symbol: "GPOR.L" },
    { name: "Greggs", symbol: "GRG.L" },
    { name: "Halfords Group", symbol: "HFD.L" },
    { name: "Hays", symbol: "HAS.L" },
    { name: "Headlam Group", symbol: "HEAD.L" },
    { name: "Henry Boot", symbol: "BOOT.L" },
    { name: "Hikma Pharmaceuticals", symbol: "HIK.L" },
    { name: "Hilton Food Group", symbol: "HFG.L" },
    { name: "Hollywood Bowl Group", symbol: "BOWL.L" },
    { name: "Homeserve", symbol: "HSV.L" },
    { name: "Howden Joinery Group", symbol: "HWDN.L" },
    { name: "Hunting", symbol: "HTG.L" },
    { name: "Hyder Consulting", symbol: "HYDR.L" },
    { name: "IG Group Holdings", symbol: "IGG.L" },
    { name: "IMI", symbol: "IMI.L" },
    { name: "Indivior", symbol: "INDV.L" },
    { name: "Inland Homes", symbol: "INL.L" },
    { name: "IntegraFin Holdings", symbol: "IHP.L" },
    { name: "Intermediate Capital Group", symbol: "ICP.L" },
    { name: "ITV", symbol: "ITV.L" },
    { name: "James Fisher and Sons", symbol: "FSJ.L" },
    { name: "JTC", symbol: "JTC.L" },
    { name: "Jupiter Fund Management", symbol: "JUP.L" },
    { name: "Just Eat Takeaway", symbol: "JET.L" },
    { name: "Kainos Group", symbol: "KNOS.L" },
    { name: "Keller Group", symbol: "KLR.L" },
    { name: "Kier Group", symbol: "KIE.L" },
    { name: "Lancashire Holdings", symbol: "LRE.L" },
    { name: "Liontrust Asset Management", symbol: "LIO.L" },
    { name: "LondonMetric Property", symbol: "LMP.L" },
    { name: "Lookers", symbol: "LOOK.L" },
    { name: "LXi REIT", symbol: "LXI.L" },
    { name: "Marston's", symbol: "MARS.L" },
    { name: "Marshalls", symbol: "MSLH.L" },
    { name: "Mattioli Woods", symbol: "MTW.L" },
    { name: "McColl's Retail Group", symbol: "MCLS.L" },
    { name: "Micro Focus International", symbol: "MCRO.L" },
    { name: "Midwich Group", symbol: "MIDW.L" },
    { name: "Moonpig Group", symbol: "MOON.L" },
    { name: "Morgan Advanced Materials", symbol: "MGAM.L" },
    { name: "Morgan Sindall Group", symbol: "MGNS.L" },
    { name: "Morrisons", symbol: "MRW.L" },
    { name: "National Express Group", symbol: "NEX.L" },
    { name: "NCC Group", symbol: "NCC.L" },
    { name: "Network International Holdings", symbol: "NETW.L" },
    { name: "NewRiver REIT", symbol: "NRR.L" },
    { name: "NMC Health", symbol: "NMC.L" },
    { name: "Novacyt", symbol: "NCYT.L" },
    { name: "OneSavings Bank", symbol: "OSB.L" },
    { name: "Oxford Instruments", symbol: "OXIG.L" },
    { name: "Paragon Banking Group", symbol: "PAG.L" },
    { name: "PayPoint", symbol: "PAY.L" },
    { name: "Pennon Group", symbol: "PNN.L" },
    { name: "Pepco Group", symbol: "PPCO.L" },
    { name: "Pets at Home Group", symbol: "PETS.L" },
    { name: "Polymetal International", symbol: "POLY.L" },
    { name: "Porvair", symbol: "PRV.L" },
    { name: "Premier Foods", symbol: "PFD.L" },
    { name: "PureTech Health", symbol: "PRTC.L" },
    { name: "PZ Cussons", symbol: "PZC.L" },
    { name: "QinetiQ Group", symbol: "QQ.L" },
    { name: "Quattro Energy Holdings", symbol: "QUAT.L" },
    { name: "Rank Group", symbol: "RNK.L" },
    { name: "Reach", symbol: "RCH.L" },
    { name: "Record", symbol: "REC.L" },
    { name: "Redde Northgate", symbol: "REDD.L" },
    { name: "Restore", symbol: "RST.L" },
    { name: "Revolution Bars Group", symbol: "RBG.L" },
    { name: "Ricardo", symbol: "RCDO.L" },
    { name: "Rio Tinto", symbol: "RIO.L" },
    { name: "Robert Walters", symbol: "RWA.L" },
    { name: "Rotork", symbol: "ROR.L" },
    { name: "Royal Bank of Canada", symbol: "RY.L" },
    { name: "S4 Capital", symbol: "SFOR.L" },
    { name: "Safestore Holdings", symbol: "SAFE.L" },
    { name: "Savills", symbol: "SVS.L" },
    { name: "Serica Energy", symbol: "SQZ.L" },
    { name: "Serco Group", symbol: "SRP.L" },
    { name: "Shaftesbury", symbol: "SHB.L" },
    { name: "SIG", symbol: "SHI.L" },
    { name: "Signature Aviation", symbol: "SIG.L" },
    { name: "Skuld Holdings", symbol: "SKU.L" },
    { name: "Smart Metering Systems", symbol: "SMS.L" },
    { name: "Softcat", symbol: "SCT.L" },
    { name: "Sophos Group", symbol: "SOPH.L" },
    { name: "Spectris", symbol: "SXS.L" },
    { name: "Spire Healthcare Group", symbol: "SPI.L" },
    { name: "Starwood European Real Estate Finance", symbol: "SWEF.L" },
    { name: "Strix Group", symbol: "KETL.L" },
    { name: "Superdry", symbol: "SDRY.L" },
    { name: "SThree", symbol: "STEM.L" },
    { name: "TCLARKE", symbol: "CTO.L" },
    { name: "Team17 Group", symbol: "TM17.L" },
    { name: "TechnipFMC", symbol: "FTI.L" },
    { name: "The Big Food Group", symbol: "BFG.L" },
    { name: "The Gym Group", symbol: "GYM.L" },
    { name: "TI Fluid Systems", symbol: "TIFS.L" },
    { name: "TP ICAP", symbol: "TCAP.L" },
    { name: "Travis Perkins", symbol: "TPK.L" },
    { name: "TUI AG", symbol: "TUI.L" },
    { name: "Tullow Oil", symbol: "TLW.L" },
    { name: "Ultra Electronics Holdings", symbol: "ULE.L" },
    { name: "Urban Logistics REIT", symbol: "SHED.L" },
    { name: "Valneva", symbol: "VLA.L" },
    { name: "Victrex", symbol: "VCT.L" },
    { name: "Virgin Money UK", symbol: "VMUK.L" },
    { name: "Wetherspoon (J D)", symbol: "JDW.L" },
    { name: "WH Smith", symbol: "SMWH.L" },
    { name: "Workspace Group", symbol: "WKP.L" },
    { name: "XPS Pensions Group", symbol: "XPS.L" },
    { name: "YouGov", symbol: "YOU.L" },
    { name: "Zegona Communications", symbol: "ZEG.L" }
];

const usStocks = [
    { name: "Apple Inc", symbol: "AAPL" },
    { name: "Microsoft Corporation", symbol: "MSFT" },
    { name: "Amazon.com Inc", symbol: "AMZN" },
    { name: "NVIDIA Corporation", symbol: "NVDA" },
    { name: "Alphabet Inc Class A", symbol: "GOOGL" },
    { name: "Tesla Inc", symbol: "TSLA" },
    { name: "Meta Platforms Inc", symbol: "META" },
    { name: "Berkshire Hathaway Inc Class B", symbol: "BRK-B" },
    { name: "Taiwan Semiconductor", symbol: "TSM" },
    { name: "ASML Holding N.V.", symbol: "ASML" },
    { name: "UnitedHealth Group Inc", symbol: "UNH" },
    { name: "Eli Lilly and Company", symbol: "LLY" },
    { name: "JPMorgan Chase & Co", symbol: "JPM" },
    { name: "Visa Inc Class A", symbol: "V" },
    { name: "Broadcom Inc", symbol: "AVGO" },
    { name: "Johnson & Johnson", symbol: "JNJ" },
    { name: "Walmart Inc", symbol: "WMT" },
    { name: "Mastercard Inc Class A", symbol: "MA" },
    { name: "Procter & Gamble Co", symbol: "PG" },
    { name: "Home Depot Inc", symbol: "HD" },
    { name: "Novo Nordisk A/S", symbol: "NVO" },
    { name: "Exxon Mobil Corporation", symbol: "XOM" },
    { name: "ASML", symbol: "ASML" },
    { name: "Bank of America Corp", symbol: "BAC" },
    { name: "Chevron Corporation", symbol: "CVX" },
    { name: "AbbVie Inc", symbol: "ABBV" },
    { name: "Oracle Corporation", symbol: "ORCL" },
    { name: "Coca-Cola Co", symbol: "KO" },
    { name: "Salesforce Inc", symbol: "CRM" },
    { name: "Adobe Inc", symbol: "ADBE" },
    { name: "Netflix Inc", symbol: "NFLX" },
    { name: "Costco Wholesale Corp", symbol: "COST" },
    { name: "Tesla Inc", symbol: "TSLA" },
    { name: "PayPal Holdings Inc", symbol: "PYPL" },
    { name: "Intel Corporation", symbol: "INTC" },
    { name: "Pfizer Inc", symbol: "PFE" },
    { name: "Walt Disney Co", symbol: "DIS" },
    { name: "Cisco Systems Inc", symbol: "CSCO" },
    { name: "Verizon Communications", symbol: "VZ" },
    { name: "AT&T Inc", symbol: "T" },
    { name: "Comcast Corp Class A", symbol: "CMCSA" },
    { name: "PepsiCo Inc", symbol: "PEP" },
    { name: "Thermo Fisher Scientific", symbol: "TMO" },
    { name: "Danaher Corporation", symbol: "DHR" },
    { name: "McDonald's Corp", symbol: "MCD" },
    { name: "Abbott Laboratories", symbol: "ABT" },
    { name: "Wells Fargo & Co", symbol: "WFC" },
    { name: "Nike Inc Class B", symbol: "NKE" },
    { name: "Merck & Co Inc", symbol: "MRK" },
    { name: "Advanced Micro Devices", symbol: "AMD" },
    { name: "Texas Instruments Inc", symbol: "TXN" },
    { name: "Qualcomm Inc", symbol: "QCOM" },
    { name: "IBM Corp", symbol: "IBM" },
    { name: "Linde PLC", symbol: "LIN" },
    { name: "United Parcel Service", symbol: "UPS" },
    { name: "Philip Morris International", symbol: "PM" },
    { name: "Honeywell International", symbol: "HON" },
    { name: "Union Pacific Corp", symbol: "UNP" },
    { name: "Caterpillar Inc", symbol: "CAT" },
    { name: "American Express Co", symbol: "AXP" },
    { name: "Goldman Sachs Group", symbol: "GS" },
    { name: "Booking Holdings Inc", symbol: "BKNG" },
    { name: "Accenture PLC Class A", symbol: "ACN" },
    { name: "Bristol-Myers Squibb", symbol: "BMY" },
    { name: "Amgen Inc", symbol: "AMGN" },
    { name: "Lockheed Martin Corp", symbol: "LMT" },
    { name: "General Electric Co", symbol: "GE" },
    { name: "Starbucks Corp", symbol: "SBUX" },
    { name: "3M Co", symbol: "MMM" },
    { name: "ServiceNow Inc", symbol: "NOW" },
    { name: "Medtronic PLC", symbol: "MDT" },
    { name: "Elevance Health Inc", symbol: "ELV" },
    { name: "Deere & Co", symbol: "DE" },
    { name: "BlackRock Inc", symbol: "BLK" },
    { name: "Gilead Sciences Inc", symbol: "GILD" },
    { name: "Charles Schwab Corp", symbol: "SCHW" },
    { name: "Citigroup Inc", symbol: "C" },
    { name: "Morgan Stanley", symbol: "MS" },
    { name: "CVS Health Corp", symbol: "CVS" },
    { name: "Raytheon Technologies", symbol: "RTX" },
    { name: "Applied Materials Inc", symbol: "AMAT" },
    { name: "Intuitive Surgical Inc", symbol: "ISRG" },
    { name: "ConocoPhillips", symbol: "COP" },
    { name: "Airbnb Inc Class A", symbol: "ABNB" },
    { name: "Snowflake Inc Class A", symbol: "SNOW" },
    { name: "Moderna Inc", symbol: "MRNA" },
    { name: "Zoom Video Communications", symbol: "ZM" },
    { name: "Peloton Interactive", symbol: "PTON" },
    { name: "Palantir Technologies", symbol: "PLTR" },
    { name: "Roblox Corp Class A", symbol: "RBLX" },
    { name: "Rivian Automotive", symbol: "RIVN" },
    { name: "Block Inc", symbol: "SQ" },
    { name: "Twilio Inc Class A", symbol: "TWLO" },
    { name: "Roku Inc Class A", symbol: "ROKU" },
    { name: "MongoDB Inc", symbol: "MDB" },
    { name: "Cloudflare Inc Class A", symbol: "NET" },
    { name: "Unity Software Inc", symbol: "U" },
    { name: "DocuSign Inc", symbol: "DOCU" },
    { name: "Shopify Inc Class A", symbol: "SHOP" },
    { name: "CrowdStrike Holdings", symbol: "CRWD" },
    { name: "Datadog Inc Class A", symbol: "DDOG" },
    { name: "Okta Inc Class A", symbol: "OKTA" },
    { name: "Zscaler Inc", symbol: "ZS" },
    { name: "Splunk Inc", symbol: "SPLK" },
    { name: "Elastic N.V.", symbol: "ESTC" },
    { name: "PagerDuty Inc", symbol: "PD" },
    { name: "Fastly Inc Class A", symbol: "FSLY" }
];

const marketIndices = [
    { name: "NIFTY 50", symbol: "^NSEI" },
    { name: "NIFTY Next 50", symbol: "^NIFTY_NEXT_50" },
    { name: "NIFTY Midcap 150", symbol: "^NIFTY_MIDCAP_150" },
    { name: "FTSE 100", symbol: "^FTSE" },
    { name: "FTSE 250", symbol: "^FTMC" },
    { name: "S&P 500", symbol: "^GSPC" },
    { name: "NASDAQ Composite", symbol: "^IXIC" },
    { name: "Dow Jones Industrial Average", symbol: "^DJI" }
];

// Export functions
function getStockLists() {
    return {
        nifty50: nifty50Stocks,
        niftyNext50: niftyNext50Stocks,
        niftyMidcap150: niftyMidcap150Stocks,
        ftse100: ftse100Stocks,
        ftse250: ftse250Stocks,
        usStocks: usStocks,
        indices: marketIndices
    };
}

function getAllStocks() {
    const lists = getStockLists();
    return [
        ...lists.nifty50,
        ...lists.niftyNext50,
        ...lists.niftyMidcap150,
        ...lists.ftse100,
        ...lists.ftse250,
        ...lists.usStocks
    ];
}

function getStocksByMarket(market) {
    const lists = getStockLists();
    return lists[market] || [];
}

// Export for Node.js (backend)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        getStockLists,
        getAllStocks,
        getStocksByMarket,
        nifty50Stocks,
        niftyNext50Stocks,
        niftyMidcap150Stocks,
        ftse100Stocks,
        ftse250Stocks,
        usStocks,
        marketIndices
    };
}

// Export for Browser (frontend)
if (typeof window !== 'undefined') {
    window.StockData = {
        getStockLists,
        getAllStocks,
        getStocksByMarket
    };
}