window.SALegal = {
  terms: {
    title: 'Terms of service',
    updated: 'Last updated 8 August 2026',
    sections: [
      { id: 'what', heading: 'What SutrAlgo is', body: [
        'SutrAlgo is an educational tool. It shows what one mechanical trading rule found in the past and what it is finding now. It is not investment advice, a recommendation, or a broker.',
        'Nothing in the app knows your circumstances. Decisions about your money are yours alone.' ] },
      { id: 'account', heading: 'Your account', body: [
        'You sign in with Google and we receive your name and email. One account per person; keep access to your email, because it is how the account is recovered.',
        'You must be 18 or older and able to enter a contract where you live.' ] },
      { id: 'plans', heading: 'Plans and payment', body: [
        'Explorer is free for 90 days with no card. Trader is billed monthly in your regional currency, at the price shown when you subscribed, fixed for 12 months.',
        'Cancel any time from your account page — access continues to the end of the month you have paid for. The 14-day money-back guarantee applies to your first payment.' ] },
      { id: 'signals', heading: 'Signals and performance', body: [
        'Signals are generated by a fixed formula applied to market data. They can be wrong, late, or absent, and past performance is not a reliable indicator of future results.',
        'We show the formula\'s full record, losses included, and we do not edit history.' ] },
      { id: 'liability', heading: 'Liability', body: [
        'To the fullest extent the law allows, SutrAlgo is not liable for trading losses, missed opportunities, or decisions made using the app.',
        'Nothing in these terms limits liability where the law does not allow it to be limited.' ] },
      { id: 'changes', heading: 'Changes to these terms', body: [
        'When the terms change materially we email every account 30 days before the change applies. Continuing to use SutrAlgo after that date accepts the new terms.' ] }
    ]
  },
  privacy: {
    title: 'Privacy policy',
    updated: 'Last updated 8 August 2026',
    sections: [
      { id: 'collect', heading: 'What we collect', body: [
        'Your name and email from Google sign-in, your country for pricing, the positions and trades you record, and — only if you connect the bot — your Telegram chat id.',
        'We do not collect card numbers (the payment provider handles those), broker credentials, or precise location.' ] },
      { id: 'use', heading: 'How it is used', body: [
        'To run your account, send the alerts you asked for, bill the right amount in the right currency, and keep the service working. We do not sell or share your data for advertising.' ] },
      { id: 'where', heading: 'Where it lives', body: [
        'Data is stored with our hosting provider in the EU, encrypted in transit and at rest. Payment details live with Stripe or Razorpay under their own policies.' ] },
      { id: 'rights', heading: 'Your rights', body: [
        'Export everything from the Your data page at any time; deletion from the same page removes your account and data within 30 days, with backups aging out inside 90.',
        'You can also email privacy@sutralgo.com to exercise any right UK GDPR gives you.' ] },
      { id: 'cookies', heading: 'Cookies', body: [
        'One cookie keeps you signed in and one remembers your theme. There is no advertising or cross-site tracking.' ] }
    ]
  }
};
